### ISSUE TITLE
 Cambio en tabla de factores para cálculo de la prima

### ISSUE THREAD

**Issue by cmonsalvec** [rxsh96/is2-prima#5]
Estimados,

De acuerdo a las estadísticas del 2019 hemos comprobado que la siniestralidad de conductores de 65 años de edad o más ha aumentado. Por tal razón el directorio de nuestra empresa ha decidido modificar para este rango de edad el número de puntos que puede perder en su licencia de conducir. El directorio ha aprobado que ese número de puntos pase de 5 a 4.

Por favor realizar los cambios en el sistema para que esta nueva disposición del directorio pueda entrar en funcionamiento.

**Comment by rxsh96** [comment]
Abriendo Ticket para atender su requerimiento. 

/cc @cmonsalvec  @alexgor10  @Menarin

**Comment by rxsh96** [comment]
Se ha comprobado que el requerimiento es nuevo. 

/cc @cmonsalvec  @alexgor10 @Menarin

**Comment by rxsh96** [comment]
Se procedió a categorizar el incidente.
Estimado usuario @cmonsalvec, ¿está de acuerdo con la categorización?

/cc @alexgor10 @Menarin

**Comment by cmonsalvec** [comment]
No veo que hayan indicado a que milestone del proyecto está relacionado este cliente. También sería conveniente una categorización del tipo: bug, mejora requerida, adaptación requerida, etc. (algo así).

**Comment by rxsh96** [comment]
Gracias por su observación. Se especificó el milestone y agregaron nuevas categorías. 

Se procede a asignar el incidente a un miembro del equipo.

/cc @cmonsalvec  @alexgor10  @Menarin

**Comment by Menarin** [comment]
Se trabajó en la resolución del issue, con el commit : https://github.com/rxsh96/is2-prima/commit/c99edf625bda16f9b3360212d83e242875cd4fca
Se procede a la fase de testing.
/cc @cmonsalvec @alexgor10 @rxsh96

**Comment by cmonsalvec** [comment]
Agradecería me comuniquen el plan de pruebas que han decidido realizar

**Comment by rxsh96** [comment]
Con el nuevo requerimiento, el plan de pruebas que se definió inicialmente sufre una ligera modificación, por tal motivo adjunto documento para su revisión.

[IS2_IssuesTrackingTestPlan.pdf](https://github.com/rxsh96/is2-prima/files/4084194/IS2_IssuesTrackingTestPlan.pdf)

/cc @cmonsalvec @Menarin @alexgor10

**Comment by cmonsalvec** [comment]
ok, muchas gracias.

**Comment by rxsh96** [comment]
Continuando con las pruebas

**Pruebas de Integración**
No aplica, pues sólo existe un módulo. 

Realizando las pruebas descritas en el documento anterior.
Adjuntamos captura de haberlas pasado exitosamente. 
![image](https://user-images.githubusercontent.com/22757782/72838400-34e16300-3c5e-11ea-938c-acf49ea04489.png)

La siguiente fase son las pruebas de aceptación.

**Comment by alexgor10** [comment]
**Pruebas de aceptación realizadas y verificadas.** 
Se realizaron las pruebas de aceptación, se adjuntan los casos: 

![image](https://user-images.githubusercontent.com/32745067/72839787-ebdede00-3c60-11ea-8e1d-f4722ac396c4.png)

![image](https://user-images.githubusercontent.com/32745067/72839808-f600dc80-3c60-11ea-8b9a-fa45d30265f5.png)

/cc @rxsh96  @Menarin.

/cc @cmonsalvec.  ¿Está usted de acuerdo con las pruebas realizadas?.

**Comment by cmonsalvec** [comment]
Perfecto, muchas gracias por positivamente atender este requerimiento.

**Comment by alexgor10** [comment]
**Verificación de Completitud.** 

**_Etapas_**
- Reporte de incidente - REVISADO
- Reproducción del problema - REALIZADO
- Asignaciones - REALIZADO
- Análisis del impacto - REALIZADO
- Solución del incidente - REALIZADO
- Pruebas de sistema e integración - APROBADA
- Prueba de aceptación - APROBADA

**Incidente Resuelto**

¿Estimado @cmonsalvec  se puede proceder al cierre del ticket?

**Comment by cmonsalvec** [comment]
Si, pueden proceder al cierre. Gracias
